CHORE: DTO, Repository and Profile added
Pimbosly/DOTNET_Final_Case pull request #3
Opened 2022-06-02 15:04 UTC by VictorRosaValdez

DTO, Repository and Profile added.

2022-06-02 15:16 UTC, Leroy96 approved these changes
Ziet er goed uit! Alleen veel onnodige witregels, maar dat kunnen we er later uithalen.

2022-06-02 17:32 UTC, Pimbosly commented on DOTNET_Final_Case_BackEnd/Program.cs
> +
feels a little much whitelines

2022-06-02 17:34 UTC, Pimbosly requested changes
redelijk wat whitelines bij de interfaces en profiles.
Code ziet er voor de rest goed uit.

2022-06-03 07:03 UTC, Dorine-forritari reviewed
Great work! I think in the ProjectCreateDTO and ProjectReadDTO we should make Industry a compulsory field instead of nullable (so we always know which Industry a project belong to and the design will also depend on that with the icons). Maybe for the Description as well, what do you guys think? And in the repositories in the comments 'Abstract method for ...' -> ' Abstract method to....' (English grammar ;))

2022-06-03 07:56 UTC, VictorRosaValdez commented on DOTNET_Final_Case_BackEnd/Program.cs
> +
White lines were deleted.

2022-06-03 08:07 UTC, VictorRosaValdez commented
Feedback processed.

2022-06-03 08:07 UTC, merged